AllCops:
  NewCops: enable
  Exclude:
    - examples/**/*
    - gemfiles/*
    - vendor/**/*
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Layout:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - spec/**/*
